# prise en main de TENSORFLOW

# CHARGER LE PACKAGE

In [135]:
%pylab inline
import tensorflow as tf
print ("PACKAGES LOADED")

Populating the interactive namespace from numpy and matplotlib
PACKAGES LOADED


# DEBUTER UNE SESSION DE CALCUL TENSORFLOW

In [169]:
sess = tf.InteractiveSession()

# CONSTANTES TF

In [170]:
a = tf.constant(1.5)
b = tf.constant(0.5)
c = a+b
print(a)
print(b)
print(c)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)


# Demandons a TF d'executer le graphe pour nous donner la valeur de ses noeuds

In [171]:
print( sess.run(a) )

b_out = sess.run(b)
print(b_out)

print( sess.run(c) )

1.5
0.5
2.0


In [172]:
print( type(b_out) )
print( type(b) )
print( type(c) )

<type 'numpy.float32'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


# OPERATIONS

In [173]:
a_plus_ = a + b + 3 + 4*b
print(a_plus_)

Tensor("add_4:0", shape=(), dtype=float32)


In [174]:
sess.run(a_plus_)

7.0

In [175]:
sess.run(a * b)

0.75

In [176]:
r = tf.random_normal([5, 2])
print( r )

Tensor("random_normal_1:0", shape=(5, 2), dtype=float32)


In [177]:
sess.run( r )

array([[-1.61783433,  1.01691806],
       [ 1.72664416,  1.05164361],
       [ 1.41766095,  0.59574431],
       [-1.00064051, -0.21502699],
       [ 0.083224  , -0.90700072]], dtype=float32)

In [178]:
sess.run( tf.linspace(0.0,1.0,6) )

array([ 0.        ,  0.2       ,  0.40000001,  0.60000002,  0.80000001,  1.        ], dtype=float32)

# VARIABLES

In [179]:
weight = tf.Variable( tf.random_normal([5, 2]) ,name='w')
bias   = tf.Variable( 0.5 ,name='b')

In [180]:
print(weight)
print('dimension de la variable = ',weight.get_shape() )
print(bias)

Tensor("w_1/read:0", shape=(5, 2), dtype=float32)
('dimension de la variable = ', TensorShape([Dimension(5), Dimension(2)]))
Tensor("b_1/read:0", shape=(), dtype=float32)


In [181]:
weight_out = sess.run(weight)
print(weight_out)

bias_out = sess.run(weight)
print(bias_out)

FailedPreconditionError: Attempting to use uninitialized value w_1
	 [[Node: _send_w_1_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1929639033372823985, tensor_name="w_1:0", _device="/job:localhost/replica:0/task:0/cpu:0"](w_1)]]

# Pourquoi cette erreur ?

In [183]:
init = tf.global_variables_initializer()
sess.run(init)
print ("INITIALIZATION")

INITIALIZATION


In [163]:
weight_out = sess.run(weight)
print(weight_out)
print()

bias_out = sess.run(bias)
print(bias_out)

ValueError: Fetch argument <tensorflow.python.ops.variables.Variable object at 0x10dcaf610> cannot be interpreted as a Tensor. (Tensor Tensor("w:0", shape=(5, 2), dtype=float32_ref) is not an element of this graph.)

# PLACEHOLDERS (receptables à données)

In [160]:
x = tf.placeholder(tf.float32, [None, 5])
print(x)

Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


## OPERATION AVEC DES VARIABLES ET DES PLACEHOLDERS

In [161]:
oper = tf.matmul(x, weight)

ValueError: Tensor("w:0", shape=(5, 2), dtype=float32_ref) must be from the same graph as Tensor("Placeholder:0", shape=(?, 5), dtype=float32).

In [128]:
data = random.rand(1, 5)
data

array([[ 0.25329566,  0.07794091,  0.72627324,  0.122866  ,  0.25040388]])

In [129]:
oper_out = sess.run(oper, feed_dict={x: data})
print(oper_out)

[[ 0.94517928 -0.24772742]]


In [130]:
data = np.random.rand(2, 5)
sess.run(oper, feed_dict={x: data})

array([[ 1.72427475, -0.44801798],
       [ 1.79008484, -1.32111287]], dtype=float32)

# Exercice 1

* creez une variable tensorflow initialisee par matrice identite de taille 3 
* creez un vecteur constant tensorflow de dimension 2
* faites le produit des deux et affichez le

# Exercice 2

* créez un placeholder de dimension (1,4)
* creez une operation qui renvoie la somme des carres de ce placeholder
* alimentez le placeholder avec le vecteur [1.0,2.0,3.0,4.0] et verifiez le resultat

# TensorBoard
###### dans le terminal, tapez:
    mkdir /tmp/logs
    rm /tmp/logs/*
    tensorboard --logdir=/tmp/logs
###### dans le navigateur, ouvrez http://localhost:6006/ 

In [154]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

In [155]:
x = tf.Variable([2.0,4.0],name='x')
z= (x**2)+3*x

In [156]:
init = tf.global_variables_initializer()
sess.run(init)
sess.run(z)

array([ 10.,  28.], dtype=float32)

In [157]:
summary_writer = tf.summary.FileWriter('/tmp/logs', graph=sess.graph,flush_secs=10)

In [113]:
with tf.name_scope('gros_bout'):
    w = x+x+x+x+z+z+z+z

In [158]:
with tf.name_scope('pas_tres_utiles'):
    with tf.name_scope('produit_scalaire'):
        m1 = tf.reshape(x,(2,1))
        m2 = tf.reshape(x,(1,2))
        s  = tf.matmul(m2,m1)
    with tf.name_scope('moyenne'):
        moy = tf.reduce_mean(x)
        mx  = tf.reduce_max(x)

In [159]:
sess.run([moy,mx,s,w,x])

ValueError: Fetch argument <tf.Tensor 'gros_bout/add_6:0' shape=(2,) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("gros_bout/add_6:0", shape=(2,), dtype=float32) is not an element of this graph.)